features : 
  [
    [Conv, [64, 3, 1, 1]],   # 0: Conv2d with 3 input channels, 64 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [64]],       # 1: BatchNorm2d with 64 features
    [ReLU, []],              # 2: ReLU activation
    [Conv, [64, 3, 1, 1]],   # 3: Conv2d with 64 input channels, 64 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [64]],       # 4: BatchNorm2d with 64 features
    [ReLU, []],              # 5: ReLU activation
    [MaxPool, [2, 2, 0]],    # 6: MaxPool2d with 2x2 kernel, stride 2, no padding
    [Conv, [128, 3, 1, 1]],  # 7: Conv2d with 64 input channels, 128 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [128]],      # 8: BatchNorm2d with 128 features
    [ReLU, []],              # 9: ReLU activation
    [Conv, [128, 3, 1, 1]],  # 10: Conv2d with 128 input channels, 128 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [128]],      # 11: BatchNorm2d with 128 features
    [ReLU, []],              # 12: ReLU activation
    [MaxPool, [2, 2, 0]],    # 13: MaxPool2d with 2x2 kernel, stride 2, no padding
    [Conv, [256, 3, 1, 1]],  # 14: Conv2d with 128 input channels, 256 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [256]],      # 15: BatchNorm2d with 256 features
    [ReLU, []],              # 16: ReLU activation
    [Conv, [256, 3, 1, 1]],  # 17: Conv2d with 256 input channels, 256 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [256]],      # 18: BatchNorm2d with 256 features
    [ReLU, []],              # 19: ReLU activation
    [Conv, [256, 3, 1, 1]],  # 20: Conv2d with 256 input channels, 256 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [256]],      # 21: BatchNorm2d with 256 features
    [ReLU, []],              # 22: ReLU activation
    [MaxPool, [2, 2, 0]],    # 23: MaxPool2d with 2x2 kernel, stride 2, no padding
    [Conv, [512, 3, 1, 1]],  # 24: Conv2d with 256 input channels, 512 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [512]],      # 25: BatchNorm2d with 512 features
    [ReLU, []],              # 26: ReLU activation
    [Conv, [512, 3, 1, 1]],  # 27: Conv2d with 512 input channels, 512 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [512]],      # 28: BatchNorm2d with 512 features
    [ReLU, []],              # 29: ReLU activation
    [Conv, [512, 3, 1, 1]],  # 30: Conv2d with 512 input channels, 512 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [512]],      # 31: BatchNorm2d with 512 features
    [ReLU, []],              # 32: ReLU activation
    [MaxPool, [2, 2, 0]],    # 33: MaxPool2d with 2x2 kernel, stride 2, no padding
    [Conv, [512, 3, 1, 1]],  # 34: Conv2d with 512 input channels, 512 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [512]],      # 35: BatchNorm2d with 512 features
    [ReLU, []],              # 36: ReLU activation
    [Conv, [512, 3, 1, 1]],  # 37: Conv2d with 512 input channels, 512 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [512]],      # 38: BatchNorm2d with 512 features
    [ReLU, []],              # 39: ReLU activation
    [Conv, [512, 3, 1, 1]],  # 40: Conv2d with 512 input channels, 512 filters, 3x3 kernel, stride 1, padding 1
    [BatchNorm, [512]],      # 41: BatchNorm2d with 512 features
    [ReLU, []],              # 42: ReLU activation
    [MaxPool, [2, 2, 0]]     # 43: MaxPool2d with 2x2 kernel, stride 2, no padding
  ]

avgpool : 
  [
    [AdaptiveAvgPool, [7, 7]] # 0: AdaptiveAvgPool2d to output size 7x7
  ]

classifier : 
  [
    [Linear, [25088, 4096]],  # 0: Fully connected layer with 25088 input features and 4096 output features
    [ReLU, []],               # 1: ReLU activation
    [Dropout, [0.5]],         # 2: Dropout with probability 0.5
    [Linear, [4096, 4096]],   # 3: Fully connected layer with 4096 input features and 4096 output features
    [ReLU, []],               # 4: ReLU activation
    [Dropout, [0.5]],         # 5: Dropout with probability 0.5
    [Linear, [4096, 1000]]    # 6: Fully connected layer with 4096 input features and 1000 output features
  ]
